Class {
	#name : #MlsObjectRenamedChange,
	#superclass : #Object,
	#instVars : [
		'value11',
		'value22'
	],
	#category : #'MyLittleSuite-Todo-Updater'
}

{ #category : #accessing }
MlsObjectRenamedChange >> value11 [

	^ value11
]

{ #category : #accessing }
MlsObjectRenamedChange >> value11: anObject [

	value11 := anObject
]

{ #category : #accessing }
MlsObjectRenamedChange >> value22 [

	^ value22
]

{ #category : #accessing }
MlsObjectRenamedChange >> value22: anObject [

	value22 := anObject
]
